name: Build RPK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz projekt
        uses: actions/checkout@v4

      - name: Zainstaluj Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Zbuduj RPK
        run: |
          npm install
          npm run build

      - name: Udostępnij RPK
        uses: actions/upload-artifact@v4
        with:
          name: rpk-test
          path: "**/*.rpk"
